### ISSUE TITLE
How does stale session cleanup work?

### ISSUE THREAD

**Issue by binki** [makepost/connect-typeorm#5]
It appears to me that most session stores manually implement some maxAge based session cleanup sweep. After inspecting the source code and viewing the README, it doesn’t appear that such a feature exists in this package. As a result, I would expect the backend storage to continuously grow.

Can a periodic automatic deletion of stale records be added?

**Comment by makepost** [comment]
Session table does grow continuously now. Your suggestion is definitely reasonable. Going add a cleanup at the beginning of `set`, which is the only method after which more space is taken than before, and should make only the initial login slower. Would that be enough?

**Comment by binki** [comment]
@makepost I like that plan of putting the cleanup in `set`.

Additionally, I would suggest, if possible, to constrain the cleanup to remove 2 rows. I am actually not sure if this is a good idea or might cause higher resource usage. But I am concerned that the cleanup could end up trying to remove thousands of rows at a time which might be enough to take time. I think that since the expires column is indexed, a removal of 2 rows should always take a short amount of time. And even if there are lots of expired rows, it will slowly clean up the database as new sessions are created.

This should probably be configurable as an option to the constructor. In case the cleanup causes performance issues for someone, they might manually implement it and have an easy way to disable the built-in one.

If I get time before you do, I might try making a PR.

**Comment by makepost** [comment]
@binki Please ensure this does what you need, and I'll publish a minor release.

**Comment by charlex** [comment]
I know this is a little old, but @makepost's code in https://github.com/makepost/connect-typeorm/commit/8d3dd96897349b3e4caf7cd82ddf76e7a0e46370 would be helpful for me.

**Comment by makepost** [comment]
@charlex Released v1.1.0, hope it's still useful.

**Comment by charlex** [comment]
Thanks @makepost. I will give it a spin to make sure it's working well.
